# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'TVPhoneBeacon' do
  source 'https://github.com/CocoaPods/Specs.git'
  platform :ios, '8.0'
  use_frameworks!
  
  pod 'Alamofire', '~> 3.0.0-beta.3'
  pod 'AMSmoothAlert', '~> 1.0'
  pod 'EstimoteSDK'
end

target 'TVPhoneBeaconTests' do

end

target 'TVPhoneBeaconUITests' do

end

